twilio-security-tests:
    timeout: 30m
    type: instrumentation
    app: ftl/dummy.apk
    test: {{test_build}}
    device:
        # Pixel 2
        - {model: walleye, version: 27, locale: en, orientation: portrait}
        # Pixel
        - {model: sailfish, version: 25, locale: en, orientation: portrait}
        # Galaxy A5 2017
        - {model: HWMHA, version: 24, locale: en, orientation: portrait}
        # LG Nexus 5
        - {model: hammerhead, version: 23, locale: en, orientation: portrait}
        # Samsung Galaxy S9 (US)
        - {model: starqltechn, version: 26, locale: en, orientation: portrait}
        # Samsung S20
        - {model: x1q, version: 29, locale: en, orientation: portrait}
        # Pixel 5e
        - { model: redfin, version: 30, locale: en, orientation: portrait }
