twilio-verify-tests:
    timeout: 30m
    type: instrumentation
    app: ftl/dummy.apk
    test: {{test_build}}
    device:
        # LG Nexus 5
        - {model: hammerhead, version: 23, locale: en, orientation: portrait}
        # Pixel 5e
        - {model: redfin, version: 30, locale: en, orientation: portrait}
        # Pixel 2
        - {model: walleye, version: 27, locale: en, orientation: portrait}
        # Samsung S20
        - {model: x1q, version: 29, locale: en, orientation: portrait}
